= CI/CD - basic-servlet-example

This repository contains resources needed for the CI/CD process for the https://github.com/workload-assessment-openshift4/basic-servlet-example[]basic-servlet-example Tomcat application

== Helm chart

The Helm chart can be used deploy the application in an OpenShift namespace. It creates the required resources:

* Deployment
* Service
* Route
* ConfigMaps
* Secrets
* ...

== Deployment yamls

An example set of yaml resources generated by the Helm chart. This is only neede so we can easily overview the required deployment resources.

== Container image

Resources to build a container image for the application:

* Dockerfile
* Additional files required in the image

Inputs used by the build:

* Base image
* War file URL
* Additional files required in the image

TODO: Should the build run on localhost with Docker or in OpenShift BuildConfig?

== Pipelines

OpenShift-Pipeline task/pipeline definitions:

* Build pipelines: Build container image from source. Uses the container-image build. Source should come from a secured Git. Container image should be uploaded to secured Nexus image registry.
* Deploy  pipeline: Deploy application in a namespace. Uses the Helm chart with env specific values. Image is pulled from secured Nexus.

TODO: We probably should split up the build pipeline to "source build" and "image build" pipelines, so it can be used if the Java artifact is built another way.

Guideline and script is required to install it easily in a namespace.

