apiVersion: v1
kind: Service
metadata:
  name: {{ include "servlet-example.fullname" . }}
  labels:
    {{- include "servlet-example.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8778
      targetPort: 8778
      protocol: TCP
      name: 8778-tcp
    - port: 9779
      targetPort: 9779
      protocol: TCP
      name: 9779-tcp
  selector:
    {{- include "servlet-example.selectorLabels" . | nindent 4 }}
