apiVersion: v1
kind: Service
metadata:
  name: {{ include "helpers.fullname" . }}
  labels:
    {{- include "helpers.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: 8080-tcp
    - port: 8778
      targetPort: 8778
      protocol: TCP
      name: 8778-tcp
    - port: 9779
      targetPort: 9779
      protocol: TCP
      name: 9779-tcp
  selector:
    {{- include "helpers.selectorLabels" . | nindent 4 }}
    
