apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: basic-servlet-example-build-
spec:
  params:
    - name: APP_NAME
      value: basic-servlet-example
    - name: APP_GIT_REPO
      value: 'ssh://gogs@dtcc-gogs.gogs-test.svc:3022/szhong/basic-servlet-example.git'
    - name: CICD_GIT_REPO
      value: 'ssh://gogs@dtcc-gogs.gogs-test.svc:3022/szhong/openshift-pipelines.git'
    - name: GIT_REVISION
      value: master
    - name: CICD_GIT_REVISION
      value: master
    - name: IMAGE_NAME
      value: >-
        nexus-container-registry-nexus.apps.cluster-3bcb.sandbox1869.opentlc.com/tekton-basic-servlet/basic-servlet-example:latest
    - name: CONTEXT_DIR
      value: ServletSample
    - name: DOCKERFILE_DIR
      value: docker-build-pipeline/Dockerfile
    - name: BUILD_CONTEXT
      value: ServletSample/target/
  pipelineRef:
    name: basic-servlet-example-build
  serviceAccountName: pipeline
  serviceAccountNames:
  - taskName: fetch-app-repository
    serviceAccountName: build-bot
  - taskName: fetch-cicd-repository
    serviceAccountName: build-bot
  - taskName: build
    serviceAccountName: build-bot
  timeout: 1h0m0s
  workspaces:
    - name: workspace
      volumeClaimTemplate: 
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi
    - name: maven-settings
      emptyDir: {}