{{- if .Values.githubpipelinerun.enabled -}}
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: basic-servlet-example-build-{{ .Release.Revision }}
spec:
  params:
    - name: APP_NAME
      value: basic-servlet-example
    - name: APP_GIT_REPO
      value: https://github.com/workload-assessment-openshift4/basic-servlet-example.git
    - name: APP_GIT_REVISION
      value: master
    - name: APP_CONTEXT_DIR
      value: ServletSample
    - name: CICD_GIT_REPO
      value: https://github.com/workload-assessment-openshift4/basic-servlet-example-cicd.git
    - name: CICD_GIT_REVISION
      value: main
    - name: CICD_DOCKERFILE_DIR
      value: container-image
    - name: IMAGE_NAME
      value: >-
        nexus-container-registry-nexus.apps.cluster-3bcb.sandbox1869.opentlc.com/tekton-basic-servlet/basic-servlet-example:latest
  pipelineRef:
    name: basic-servlet-example-build
  serviceAccountName: pipeline
  serviceAccountNames:
  - taskName: fetch-app-repository
    serviceAccountName: build-bot
  - taskName: fetch-cicd-repository
    serviceAccountName: build-bot
  - taskName: build
    serviceAccountName: build-bot
  timeout: 1h0m0s
  workspaces:
    - name: workspace
      volumeClaimTemplate: 
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi
    - name: maven-settings
      emptyDir: {}
{{- end -}}